# 再成形

In [1]:
import polars as pl

## 横に長い / 縦に長いDataFrame

In [2]:
df = pl.DataFrame({
    'studnet': ['Alice', 'Bob', 'Charlie'],
    'math': [85, 78, 92],
    'science': [90, 82, 85],
    'history': [88, 80, 87]
})

df

shape: (3, 4)
┌─────────┬──────┬─────────┬─────────┐
│ studnet ┆ math ┆ science ┆ history │
│ ---     ┆ ---  ┆ ---     ┆ ---     │
│ str     ┆ i64  ┆ i64     ┆ i64     │
╞═════════╪══════╪═════════╪═════════╡
│ Alice   ┆ 85   ┆ 90      ┆ 88      │
│ Bob     ┆ 78   ┆ 82      ┆ 80      │
│ Charlie ┆ 92   ┆ 85      ┆ 87      │
└─────────┴──────┴─────────┴─────────┘

In [3]:
df = pl.DataFrame({
    'student': ['Alice','Alice','Alice', 'Bob','Bob','Bob', 'Charlie', 'Charlie', 'Charlie'],
    'subject': ['Math', 'Science', 'History', 'Math', 'Science', 'History', 'Math', 'Science', 'History'],
    'grade': [85, 90, 88, 78, 82, 80, 92, 85, 87]
})

df

shape: (9, 3)
┌─────────┬─────────┬───────┐
│ student ┆ subject ┆ grade │
│ ---     ┆ ---     ┆ ---   │
│ str     ┆ str     ┆ i64   │
╞═════════╪═════════╪═══════╡
│ Alice   ┆ Math    ┆ 85    │
│ Alice   ┆ Science ┆ 90    │
│ Alice   ┆ History ┆ 88    │
│ Bob     ┆ Math    ┆ 78    │
│ Bob     ┆ Science ┆ 82    │
│ Bob     ┆ History ┆ 80    │
│ Charlie ┆ Math    ┆ 92    │
│ Charlie ┆ Science ┆ 85    │
│ Charlie ┆ History ┆ 87    │
└─────────┴─────────┴───────┘

In [4]:
df.pivot(index='student', on='subject', values='grade')

shape: (3, 4)
┌─────────┬──────┬─────────┬─────────┐
│ student ┆ Math ┆ Science ┆ History │
│ ---     ┆ ---  ┆ ---     ┆ ---     │
│ str     ┆ i64  ┆ i64     ┆ i64     │
╞═════════╪══════╪═════════╪═════════╡
│ Alice   ┆ 85   ┆ 90      ┆ 88      │
│ Bob     ┆ 78   ┆ 82      ┆ 80      │
│ Charlie ┆ 92   ┆ 85      ┆ 87      │
└─────────┴──────┴─────────┴─────────┘

In [5]:
df = pl.DataFrame({
    'student': ['Alice','Alice','Alice', 'Alice','Alice','Alice', 'Bob','Bob','Bob', 'Bob','Bob','Bob'],
    'subject': ['Math', 'Math', 'Math', 'Science', 'Science', 'Science', 'Math', 'Math', 'Math', 'Science', 'Science', 'Science'],
    'grade': [85, 88, 85, 60, 66, 63, 51, 79, 62, 82, 85, 82]
})

df

shape: (12, 3)
┌─────────┬─────────┬───────┐
│ student ┆ subject ┆ grade │
│ ---     ┆ ---     ┆ ---   │
│ str     ┆ str     ┆ i64   │
╞═════════╪═════════╪═══════╡
│ Alice   ┆ Math    ┆ 85    │
│ Alice   ┆ Math    ┆ 88    │
│ Alice   ┆ Math    ┆ 85    │
│ Alice   ┆ Science ┆ 60    │
│ Alice   ┆ Science ┆ 66    │
│ …       ┆ …       ┆ …     │
│ Bob     ┆ Math    ┆ 79    │
│ Bob     ┆ Math    ┆ 62    │
│ Bob     ┆ Science ┆ 82    │
│ Bob     ┆ Science ┆ 85    │
│ Bob     ┆ Science ┆ 82    │
└─────────┴─────────┴───────┘

In [6]:
df.pivot(
    index='student',
    on='subject',
    values='grade',
    aggregate_function='mean'
)

shape: (2, 3)
┌─────────┬──────┬─────────┐
│ student ┆ Math ┆ Science │
│ ---     ┆ ---  ┆ ---     │
│ str     ┆ f64  ┆ f64     │
╞═════════╪══════╪═════════╡
│ Alice   ┆ 86.0 ┆ 63.0    │
│ Bob     ┆ 64.0 ┆ 83.0    │
└─────────┴──────┴─────────┘

`aggregate_function`を指定することによって、意味が重複しているデータの研鑽処理が実行できるのか

In [7]:
df.pivot(
    index='student',
    on='subject',
    values='grade',
    aggregate_function=pl.element().max() - pl.element().min()
)

shape: (2, 3)
┌─────────┬──────┬─────────┐
│ student ┆ Math ┆ Science │
│ ---     ┆ ---  ┆ ---     │
│ str     ┆ i64  ┆ i64     │
╞═════════╪══════╪═════════╡
│ Alice   ┆ 3    ┆ 6       │
│ Bob     ┆ 28   ┆ 3       │
└─────────┴──────┴─────────┘

In [8]:
df = pl.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie'],
    'math': [85, 78, 92],
    'science': [90, 82, 85],
    'history': [88, 80, 87]
})

df

shape: (3, 4)
┌─────────┬──────┬─────────┬─────────┐
│ student ┆ math ┆ science ┆ history │
│ ---     ┆ ---  ┆ ---     ┆ ---     │
│ str     ┆ i64  ┆ i64     ┆ i64     │
╞═════════╪══════╪═════════╪═════════╡
│ Alice   ┆ 85   ┆ 90      ┆ 88      │
│ Bob     ┆ 78   ┆ 82      ┆ 80      │
│ Charlie ┆ 92   ┆ 85      ┆ 87      │
└─────────┴──────┴─────────┴─────────┘

In [9]:
df.unpivot(
    index=['student'],
    on=['math', 'science', 'history'],
    variable_name='subject',
    value_name='grade'
)

shape: (9, 3)
┌─────────┬─────────┬───────┐
│ student ┆ subject ┆ grade │
│ ---     ┆ ---     ┆ ---   │
│ str     ┆ str     ┆ i64   │
╞═════════╪═════════╪═══════╡
│ Alice   ┆ math    ┆ 85    │
│ Bob     ┆ math    ┆ 78    │
│ Charlie ┆ math    ┆ 92    │
│ Alice   ┆ science ┆ 90    │
│ Bob     ┆ science ┆ 82    │
│ Charlie ┆ science ┆ 85    │
│ Alice   ┆ history ┆ 88    │
│ Bob     ┆ history ┆ 80    │
│ Charlie ┆ history ┆ 87    │
└─────────┴─────────┴───────┘

前のpolarsだと`.melt()`だったけれど、今のバージョンでは`.unpivot()`になったみたい。  
meltでもなんとなくわかるけれど、unpivotの方がよりわかりやすいかも

In [10]:
df = pl.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie'],
    'class': ['Math101', 'Math101', 'Math101', 'Math102', 'Math102', 'Math102'],
    'age': [20, 21, 22, 20, 21, 22],
    'semester': ['Fall', 'Fall', 'Fall', 'Spring', 'Spring', 'Spring'],
    'math': [85, 78, 92, 88, 79, 95],
    'science': [90, 82, 85, 92, 81, 87],
    'history': [88, 80, 87, 85, 82, 89]
})

df

shape: (6, 7)
┌─────────┬─────────┬─────┬──────────┬──────┬─────────┬─────────┐
│ student ┆ class   ┆ age ┆ semester ┆ math ┆ science ┆ history │
│ ---     ┆ ---     ┆ --- ┆ ---      ┆ ---  ┆ ---     ┆ ---     │
│ str     ┆ str     ┆ i64 ┆ str      ┆ i64  ┆ i64     ┆ i64     │
╞═════════╪═════════╪═════╪══════════╪══════╪═════════╪═════════╡
│ Alice   ┆ Math101 ┆ 20  ┆ Fall     ┆ 85   ┆ 90      ┆ 88      │
│ Bob     ┆ Math101 ┆ 21  ┆ Fall     ┆ 78   ┆ 82      ┆ 80      │
│ Charlie ┆ Math101 ┆ 22  ┆ Fall     ┆ 92   ┆ 85      ┆ 87      │
│ Alice   ┆ Math102 ┆ 20  ┆ Spring   ┆ 88   ┆ 92      ┆ 85      │
│ Bob     ┆ Math102 ┆ 21  ┆ Spring   ┆ 79   ┆ 81      ┆ 82      │
│ Charlie ┆ Math102 ┆ 22  ┆ Spring   ┆ 95   ┆ 87      ┆ 89      │
└─────────┴─────────┴─────┴──────────┴──────┴─────────┴─────────┘

In [11]:
df.unpivot(
    index=['student', 'class', 'age', 'semester'],
    on=['math', 'science', 'history'],
    variable_name='subject',
    value_name='grade'
)

shape: (18, 6)
┌─────────┬─────────┬─────┬──────────┬─────────┬───────┐
│ student ┆ class   ┆ age ┆ semester ┆ subject ┆ grade │
│ ---     ┆ ---     ┆ --- ┆ ---      ┆ ---     ┆ ---   │
│ str     ┆ str     ┆ i64 ┆ str      ┆ str     ┆ i64   │
╞═════════╪═════════╪═════╪══════════╪═════════╪═══════╡
│ Alice   ┆ Math101 ┆ 20  ┆ Fall     ┆ math    ┆ 85    │
│ Bob     ┆ Math101 ┆ 21  ┆ Fall     ┆ math    ┆ 78    │
│ Charlie ┆ Math101 ┆ 22  ┆ Fall     ┆ math    ┆ 92    │
│ Alice   ┆ Math102 ┆ 20  ┆ Spring   ┆ math    ┆ 88    │
│ Bob     ┆ Math102 ┆ 21  ┆ Spring   ┆ math    ┆ 79    │
│ …       ┆ …       ┆ …   ┆ …        ┆ …       ┆ …     │
│ Bob     ┆ Math101 ┆ 21  ┆ Fall     ┆ history ┆ 80    │
│ Charlie ┆ Math101 ┆ 22  ┆ Fall     ┆ history ┆ 87    │
│ Alice   ┆ Math102 ┆ 20  ┆ Spring   ┆ history ┆ 85    │
│ Bob     ┆ Math102 ┆ 21  ┆ Spring   ┆ history ┆ 82    │
│ Charlie ┆ Math102 ┆ 22  ┆ Spring   ┆ history ┆ 89    │
└─────────┴─────────┴─────┴──────────┴─────────┴───────┘

## 転置

In [12]:
df = pl.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie'],
    'math': [85, 78, 92],
    'science': [90, 82, 85],
    'history': [88, 80, 87]
})

df

shape: (3, 4)
┌─────────┬──────┬─────────┬─────────┐
│ student ┆ math ┆ science ┆ history │
│ ---     ┆ ---  ┆ ---     ┆ ---     │
│ str     ┆ i64  ┆ i64     ┆ i64     │
╞═════════╪══════╪═════════╪═════════╡
│ Alice   ┆ 85   ┆ 90      ┆ 88      │
│ Bob     ┆ 78   ┆ 82      ┆ 80      │
│ Charlie ┆ 92   ┆ 85      ┆ 87      │
└─────────┴──────┴─────────┴─────────┘

In [13]:
df.transpose(
    include_header=True,
    header_name='original_headers',
    column_names=(f"report_{count}" for count in range(1, len(df.columns)+1))
)

shape: (4, 4)
┌──────────────────┬──────────┬──────────┬──────────┐
│ original_headers ┆ report_1 ┆ report_2 ┆ report_3 │
│ ---              ┆ ---      ┆ ---      ┆ ---      │
│ str              ┆ str      ┆ str      ┆ str      │
╞══════════════════╪══════════╪══════════╪══════════╡
│ student          ┆ Alice    ┆ Bob      ┆ Charlie  │
│ math             ┆ 85       ┆ 78       ┆ 92       │
│ science          ┆ 90       ┆ 82       ┆ 85       │
│ history          ┆ 88       ┆ 80       ┆ 87       │
└──────────────────┴──────────┴──────────┴──────────┘

## 爆発する
explodeの直訳が「爆発する」なんだよなぁ。  
適切な日本語だと何になるだろう？アンパックとか？

In [14]:
df = pl.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie'],
    'math': [[85, 90, 88], [78, 82, 80], [92, 85, 87]]
})

df

shape: (3, 2)
┌─────────┬──────────────┐
│ student ┆ math         │
│ ---     ┆ ---          │
│ str     ┆ list[i64]    │
╞═════════╪══════════════╡
│ Alice   ┆ [85, 90, 88] │
│ Bob     ┆ [78, 82, 80] │
│ Charlie ┆ [92, 85, 87] │
└─────────┴──────────────┘

In [15]:
df.explode('math')

shape: (9, 2)
┌─────────┬──────┐
│ student ┆ math │
│ ---     ┆ ---  │
│ str     ┆ i64  │
╞═════════╪══════╡
│ Alice   ┆ 85   │
│ Alice   ┆ 90   │
│ Alice   ┆ 88   │
│ Bob     ┆ 78   │
│ Bob     ┆ 82   │
│ Bob     ┆ 80   │
│ Charlie ┆ 92   │
│ Charlie ┆ 85   │
│ Charlie ┆ 87   │
└─────────┴──────┘

In [16]:
df = pl.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie'],
    'math': [[85, 90, 88], [78, 82, 80], [92, 85, 87]],
    'science': [[85, 90, 88], [78, 82], [92, 85, 87]],
    'history': [[85, 90, 88], [78, 82], [92, 85, 87]]
})

df

shape: (3, 4)
┌─────────┬──────────────┬──────────────┬──────────────┐
│ student ┆ math         ┆ science      ┆ history      │
│ ---     ┆ ---          ┆ ---          ┆ ---          │
│ str     ┆ list[i64]    ┆ list[i64]    ┆ list[i64]    │
╞═════════╪══════════════╪══════════════╪══════════════╡
│ Alice   ┆ [85, 90, 88] ┆ [85, 90, 88] ┆ [85, 90, 88] │
│ Bob     ┆ [78, 82, 80] ┆ [78, 82]     ┆ [78, 82]     │
│ Charlie ┆ [92, 85, 87] ┆ [92, 85, 87] ┆ [92, 85, 87] │
└─────────┴──────────────┴──────────────┴──────────────┘

In [17]:
df.explode('math').explode('science').explode('history')

shape: (66, 4)
┌─────────┬──────┬─────────┬─────────┐
│ student ┆ math ┆ science ┆ history │
│ ---     ┆ ---  ┆ ---     ┆ ---     │
│ str     ┆ i64  ┆ i64     ┆ i64     │
╞═════════╪══════╪═════════╪═════════╡
│ Alice   ┆ 85   ┆ 85      ┆ 85      │
│ Alice   ┆ 85   ┆ 85      ┆ 90      │
│ Alice   ┆ 85   ┆ 85      ┆ 88      │
│ Alice   ┆ 85   ┆ 90      ┆ 85      │
│ Alice   ┆ 85   ┆ 90      ┆ 90      │
│ …       ┆ …    ┆ …       ┆ …       │
│ Charlie ┆ 87   ┆ 85      ┆ 85      │
│ Charlie ┆ 87   ┆ 85      ┆ 87      │
│ Charlie ┆ 87   ┆ 87      ┆ 92      │
│ Charlie ┆ 87   ┆ 87      ┆ 85      │
│ Charlie ┆ 87   ┆ 87      ┆ 87      │
└─────────┴──────┴─────────┴─────────┘

複数explodeをするにあたって、指定したカラムのlistの数が一致していない場合は、都度`.explode()`を実行する必要がある

## 分割する

In [18]:
df = pl.DataFrame({
    'OrderID': [1, 2, 3, 4, 5, 6],
    'Product': ['A', 'B', 'A', 'C', 'B', 'A'],
    'Quantity': [10, 5, 8, 7, 3, 12],
    'Region': ['North', 'South', 'North', 'West', 'South', 'West']
})

In [19]:
df.partition_by('Region')

[shape: (2, 4)
 ┌─────────┬─────────┬──────────┬────────┐
 │ OrderID ┆ Product ┆ Quantity ┆ Region │
 │ ---     ┆ ---     ┆ ---      ┆ ---    │
 │ i64     ┆ str     ┆ i64      ┆ str    │
 ╞═════════╪═════════╪══════════╪════════╡
 │ 1       ┆ A       ┆ 10       ┆ North  │
 │ 3       ┆ A       ┆ 8        ┆ North  │
 └─────────┴─────────┴──────────┴────────┘,
 shape: (2, 4)
 ┌─────────┬─────────┬──────────┬────────┐
 │ OrderID ┆ Product ┆ Quantity ┆ Region │
 │ ---     ┆ ---     ┆ ---      ┆ ---    │
 │ i64     ┆ str     ┆ i64      ┆ str    │
 ╞═════════╪═════════╪══════════╪════════╡
 │ 2       ┆ B       ┆ 5        ┆ South  │
 │ 5       ┆ B       ┆ 3        ┆ South  │
 └─────────┴─────────┴──────────┴────────┘,
 shape: (2, 4)
 ┌─────────┬─────────┬──────────┬────────┐
 │ OrderID ┆ Product ┆ Quantity ┆ Region │
 │ ---     ┆ ---     ┆ ---      ┆ ---    │
 │ i64     ┆ str     ┆ i64      ┆ str    │
 ╞═════════╪═════════╪══════════╪════════╡
 │ 4       ┆ C       ┆ 7        ┆ West   │
 │ 6       ┆ A       ┆ 12       ┆ West   │
 └─────────┴─────────┴──────────┴────────┘]

`.partition_by()`で、指定したカラムのグループごとにテーブルを分割してくれるのか。  
`.rolling()`だと元のテーブル構造を崩さずに、グループ別の情報を追加していたので、どっちを使うかはケースバイケース

In [20]:
df.partition_by('Region', include_key=False)

[shape: (2, 3)
 ┌─────────┬─────────┬──────────┐
 │ OrderID ┆ Product ┆ Quantity │
 │ ---     ┆ ---     ┆ ---      │
 │ i64     ┆ str     ┆ i64      │
 ╞═════════╪═════════╪══════════╡
 │ 1       ┆ A       ┆ 10       │
 │ 3       ┆ A       ┆ 8        │
 └─────────┴─────────┴──────────┘,
 shape: (2, 3)
 ┌─────────┬─────────┬──────────┐
 │ OrderID ┆ Product ┆ Quantity │
 │ ---     ┆ ---     ┆ ---      │
 │ i64     ┆ str     ┆ i64      │
 ╞═════════╪═════════╪══════════╡
 │ 2       ┆ B       ┆ 5        │
 │ 5       ┆ B       ┆ 3        │
 └─────────┴─────────┴──────────┘,
 shape: (2, 3)
 ┌─────────┬─────────┬──────────┐
 │ OrderID ┆ Product ┆ Quantity │
 │ ---     ┆ ---     ┆ ---      │
 │ i64     ┆ str     ┆ i64      │
 ╞═════════╪═════════╪══════════╡
 │ 4       ┆ C       ┆ 7        │
 │ 6       ┆ A       ┆ 12       │
 └─────────┴─────────┴──────────┘]

In [21]:
dfs = df.partition_by(['Region'], as_dict=True)
dfs

{('North',): shape: (2, 4)
 ┌─────────┬─────────┬──────────┬────────┐
 │ OrderID ┆ Product ┆ Quantity ┆ Region │
 │ ---     ┆ ---     ┆ ---      ┆ ---    │
 │ i64     ┆ str     ┆ i64      ┆ str    │
 ╞═════════╪═════════╪══════════╪════════╡
 │ 1       ┆ A       ┆ 10       ┆ North  │
 │ 3       ┆ A       ┆ 8        ┆ North  │
 └─────────┴─────────┴──────────┴────────┘,
 ('South',): shape: (2, 4)
 ┌─────────┬─────────┬──────────┬────────┐
 │ OrderID ┆ Product ┆ Quantity ┆ Region │
 │ ---     ┆ ---     ┆ ---      ┆ ---    │
 │ i64     ┆ str     ┆ i64      ┆ str    │
 ╞═════════╪═════════╪══════════╪════════╡
 │ 2       ┆ B       ┆ 5        ┆ South  │
 │ 5       ┆ B       ┆ 3        ┆ South  │
 └─────────┴─────────┴──────────┴────────┘,
 ('West',): shape: (2, 4)
 ┌─────────┬─────────┬──────────┬────────┐
 │ OrderID ┆ Product ┆ Quantity ┆ Region │
 │ ---     ┆ ---     ┆ ---      ┆ ---    │
 │ i64     ┆ str     ┆ i64      ┆ str    │
 ╞═════════╪═════════╪══════════╪════════╡
 │ 4       ┆ C       ┆ 7        ┆ West   │
 │ 6       ┆ A       ┆ 12       ┆ West   │
 └─────────┴─────────┴──────────┴────────┘}

これ面白いメソッドだなぁ。  
結構使い所ありそう！

In [22]:
dfs[('North',)]

shape: (2, 4)
┌─────────┬─────────┬──────────┬────────┐
│ OrderID ┆ Product ┆ Quantity ┆ Region │
│ ---     ┆ ---     ┆ ---      ┆ ---    │
│ i64     ┆ str     ┆ i64      ┆ str    │
╞═════════╪═════════╪══════════╪════════╡
│ 1       ┆ A       ┆ 10       ┆ North  │
│ 3       ┆ A       ┆ 8        ┆ North  │
└─────────┴─────────┴──────────┴────────┘